### ISSUE TITLE
Unable to debug binary located in path that contains å, ä or ö

### ISSUE THREAD

**Issue by gurka** [dshikashio/Pybag#24]
Windows 11
Python 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)] on win32
Pybag 2.2.12

Using the following code:

    from pybag import *
    dbg = UserDbg()
    dbg.create(path)

If path is "C:\\Test\Test.exe" everything works OK, but if path is "C:\\Testö\\Test.exe" there is an exception:

```
CommandLine: C:\Testö\Test.exe
Cannot execute 'C:\Testö\Test.exe', Win32 error 0n2
    ""
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python312\Lib\site-packages\pybag\userdbg.py", line 38, in create
    self._client.CreateProcess(path, DbgEng.DEBUG_PROCESS)
  File "C:\Python312\Lib\site-packages\pybag\dbgeng\idebugclient.py", line 141, in CreateProcess
    exception.check_err(hr)
  File "C:\Python312\Lib\site-packages\pybag\dbgeng\exception.py", line 60, in check_err
    raise err
OSError: -2147024894
```

I'm not sure if this is a character encoding issue or what's going on. I noticed it when I tried to use a binary within my Windows user folder (which is named SimonSandström).

**Comment by dshikashio** [comment]
A lot of the underlying methods in the various COM objects initially only supported ascii strings and later added wide string variants. Unfortunately Pybag is only using the ascii versions.

TO-DO: Convert Python strings to Windows wide strings and use W-apis were possible
